### ISSUE TITLE
Working TODO list

### ISSUE THREAD

**Issue by d99m** [ptpt/elasticsearch-dsl#3]
It would be great to have a TODO list of which queries we need to add to the builder to have a full query builder for the v1 release

**Comment by ptpt** [comment]
- [ ] aggregations https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html
- [ ] mget https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html
- [ ] full text queries https://www.elastic.co/guide/en/elasticsearch/reference/current/full-text-queries.html
